### ISSUE TITLE
filter időzítés

### ISSUE THREAD

**Issue by szepeviktor** [Jony-Shark/bbPress-extra-user-pages#4]
Nos, lenne egy kis baj.

- a pluginban a `beup/extra-user-pages` filter beolvasása `plugins_loaded`-kor történik - korán
- a sablonban a filter beállítása kicsit később töréténik

@Jony-Shark Átrakjuk a plugin indítást `after_setup_theme`-ba? Az még `init` előtt van.
https://codex.wordpress.org/Plugin_API/Action_Reference#Actions_Run_During_a_Typical_Request

**Comment by Jony-Shark** [comment]
Nem értem a problémát.

**Comment by szepeviktor** [comment]
Idővonal:

- elindul a WP
- plugins_loaded-kor nézi meg a pluginünk azt a filtert, amiben a sablon megadja a slug-ok, title-k listáját
- **ezután** after_setup_theme-kor adja meg a sablon a slug-ok, title-k listáját

így nem értesül a pluginünk arról, mit kell tegyen.

**Comment by szepeviktor** [comment]
Megjavult https://github.com/Jony-Shark/bbPress-extra-user-pages/commit/2a17504b93235833a5700dfab2dbbc4f014e4d2b
